# -*- coding: utf-8 -*-

# Generated by Django 1.10.6 on 2017-04-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivnosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=32)),
                ('aktivnost', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'aktivnosti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BarvaEpruvete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barva', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'barva_epruvete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrnaLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('poiskusi', models.IntegerField()),
                ('datum_zaklepanja', models.DateField()),
            ],
            options={
                'db_table': 'crna_lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DelovniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_prvega_obiska', models.DateField()),
                ('st_obiskov', models.IntegerField()),
                ('cas_med_dvema', models.IntegerField()),
                ('casovno_obdobje', models.DateField()),
            ],
            options={
                'db_table': 'delovni_nalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DodeljenoOsebje',
            fields=[
                ('je_zadolzena', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dodeljeno_osebje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Injekcije',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_injekcij', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'injekcije',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IzvajalecZd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('šifra', models.CharField(max_length=5, unique=True)),
                ('naziv', models.CharField(max_length=64)),
                ('naslov', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'izvajalec_zd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KontaktnaOseba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=64)),
                ('priimek', models.CharField(max_length=64)),
                ('naslov', models.CharField(max_length=128)),
                ('telefon', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'kontaktna_oseba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ljudje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('priimek', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ljudje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(blank=True, max_length=20, null=True)),
                ('naziv', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialDn',
            fields=[
                ('kolicina', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'material_dn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NamenObiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'namen_obiska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaporedna_st_obiska', models.IntegerField()),
                ('datum_obiska', models.DateField(blank=True, null=True)),
                ('predviden_datum', models.DateField(blank=True, null=True)),
                ('podrobnosti_obiska', models.TextField(blank=True, null=True)),
                ('izbran_datum', models.DateField(blank=True, null=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'obisk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdvzemKrvi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_epruvet', models.IntegerField()),
            ],
            options={
                'db_table': 'odvzem_krvi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Okolis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('šifra', models.CharField(max_length=32)),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'okolis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Osebje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('šifra', models.CharField(max_length=5, unique=True)),
                ('ime', models.CharField(max_length=64)),
                ('priimek', models.CharField(max_length=64)),
                ('telefon', models.CharField(max_length=32)),
                ('izbrisan', models.IntegerField()),
            ],
            options={
                'db_table': 'osebje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oskrba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oskrba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OstaliPodatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obvezen', models.IntegerField()),
                ('vrednost', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ostali_podatki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_kartice', models.CharField(max_length=32)),
                ('ime', models.CharField(max_length=64)),
                ('priimek', models.CharField(max_length=64)),
                ('telefon', models.CharField(max_length=64)),
                ('datum_rojstva', models.DateField()),
                ('naslov', models.CharField(max_length=128)),
                ('lastnik_racuna', models.IntegerField()),
                ('spol', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'pacient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('st_poste', models.IntegerField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'posta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SorodstvenaVez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sorodstvena_vez',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusDn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'status_dn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusObiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'status_obiska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusUr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'status_ur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipObiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'tip_obiska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UporabniskiRacun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('geslo', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'uporabniski_racun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VlogaOsebja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'vloga_osebja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaObiska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'vrsta_obiska',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaPodatka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
                ('podatkovni_tip', models.CharField(max_length=20)),
                ('enote', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vrsta_podatka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VrstaStoritve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=10)),
                ('naziv', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'vrsta_storitve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zdravila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'zdravila',
                'managed': False,
            },
        ),
    ]
