# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UporabniskiRacun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('geslo', models.CharField(max_length=128)),
            ],
            options={
                'managed': False,
                'db_table': 'uporabniski_racun',
            },
        ),
    ]
